services:
  
  # Debugging
  smtpdebug:
    build:
      context: .
      dockerfile: ./docker/smtpdebug/Dockerfile
    entrypoint: /start.sh
    ports:
      - "1025:1025"
    environment:
      - SMTP_PORT=1025
    volumes:
      - ./docker/smtpdebug/start.sh:/start.sh
  
  # task queue for celery
  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    restart: always
    ports:
      - 5432:5432
    volumes:
      - iitredis
    networks:
      - iit
  
  mockics:
    entrypoint: /start.sh
    build:
      context: .
      dockerfile: ./docker/mock_ics/Dockerfile
    ports:
      - 5002:5002
    volumes:
      - ./docker/mock_ics/start.sh:/start.sh
  
  debugiit:
    build:
      context: .
      dockerfile: ./docker/damngoodtech/Dockerfile
    ports:
      - "5000:5000"
    links:
      - redis
      - mockics
      - smtpdebug
    depends_on:
      - mockics
      - smtpdebug
    # entrypoint: /entrypoint.sh
    volumes:
      - ./config/iit-debug.yml:/app/iit.yml
  
  # database
  
  db:
    image: postgres:15.1-alpine
    container_name: db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - iitdb
    networks:
      - iit
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-example}"
      - "POSTGRES_DB=${POSTGRES_DB:-iitdev}"

    
  # No debugging
  iit:
    build:
      context: .
      dockerfile: ./docker/damngoodtech/Dockerfile
    ports:
      - "5000:5000"
    entrypoint: /entrypoint.sh
    volumes:
      - ./config/iit.yml:/app/iit.yml
      - ./docker/mock_ics/start.sh:/start.sh

networks:
  iit:
    name: iit